### ISSUE TITLE
맥에서의 동작 문제

### ISSUE THREAD

**Issue by yhk1038** [mrchypark/naverNewsParser#1]
` source(“getnavernews.R”,encoding=“UTF-8”) `
위 코드를 입력했을 때 mac 환경의 R console 에서는 아무런 dialog도 나타나지 않습니다.
윈도우 환경의 R console 에서는 위 코드로부터 dialog를 통해 진행되는 것으로 보이는데,
이것이 소스 상의 문제일까 싶어 질문드립니다.
혹은 소스 상의 문제가 아니라면 mac의 default setting 문제일 것 같은데
어떻게 제가 trouble shooting 이 할 수 있는지도 궁금합니다.

위 코드를 실행하기 위한 저의 console 코드 및 디렉토리 구조는 단지 다음과 같습니다:
```
# Code

root_dir <- "~/Desktop/R_lab/class_crawler/naver_news"
setwd(root_dir)
getwd()
[1] "/Users/apple/Desktop/R_lab/class_crawler/naver_news"

source(“getnavernews.R”,encoding=“UTF-8”)
```

```
# Directory : '/Users/apple/Desktop/R_lab'

├── class_crawler
│   ├── naver_news
│   │   ├── getnavernews.R
│   │   ├── naverNewsParser
│   │   │   └── README.md
│   │   └── script.R
```

**Comment by mrchypark** [comment]
@yhk1038 안녕하세요 이렇게 이슈 남겨주셔서 대단히 감사합니다! 관련 코드를 사용하시려는 부분이 어디인지 제가 잘 모르겠으나 카테고리 내의 뉴스 수집을 위해서는 readme에 작성해둔 것 처럼 N2H4라고 따로 패키지화 해서 내용을 이전하였습니다. 이 코드는 제가 더 이상 관리하지 않으려 합니다.

관심 가져주셔서 감사드리고, N2H4 패키지의 wiki 페이지를 보시면 원하시는 코드가 있을 것 같습니다. 맥에서 동작하는 것도 확인하였습니다만, 혹시 동작이 안되시면 알려주세요 감사합니다.

**Comment by yhk1038** [comment]
감사합니다! 목적이 있는 사용은 아니고 공부 차 찾아보다가 사용해보게 되었습니다. N2H4를 통해 진행해보겠습니다. 빠르고 친절한 답변 감사드립니다!
